# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Jellog
description: >- # this means to ignore newlines until "baseurl:"
  This is JellyBear's Life Blog
baseurl: "" # the subpath of the site
url: "https://gppo66.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
# Analytics
analytics:
  provider:
    "google-gtag"
    # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id: "G-ESL2TPBWLN"
    anonymize_ip: # true, false (default)
header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: gppo66@naver.com
      link: mailto:gppo66@naver.com
    - name: Kakaotalk
      value: KakaoTalk
      link: https://open.kakao.com/o/siRHhK4d

  follow:
    - name: Facebook
      link: https://www.facebook.com/parkgyeonghun
    - name: Instagram
      link: https://www.instagram.com/jellybear_pgh/
    - name: Roketpunch
      link: https://www.rocketpunch.com/@gppo66
    - name: Programmers
      link: https://programmers.co.kr/pr/gppo66_9803
    - name: GitHub
      link: http://github.com/gppo66
    - name: RSS
      link: /feed.xml

# Build settings
markdown: kramdown
sass:
  style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1.1
